version: '3.8'

services:
  web:
    build: ./backend
    ports:
      - "8000:80"
    environment:
      - DB_HOST=postgres
      - DB_NAME=shopping_db
      - DB_USER=shopping_user
      - DB_PASS=shopping_pass
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend:/var/www/html

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: shopping_db
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: shopping_pass
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shopping_user -d shopping_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: