apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-api
  template:
    metadata:
      labels:
        app: shopping-api
    spec:
      containers:
        - name: shopping-api
          image: shopping-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_NAME
              value: "shopping_db"
            - name: DB_USER
              value: "shopping_user"
            - name: DB_PASS
              value: "shopping_pass"
            - name: DB_PORT
              value: "5432"
          readinessProbe:
            httpGet:
              path: /items
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /items
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-service
spec:
  selector:
    app: shopping-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-api-loadbalancer
spec:
  selector:
    app: shopping-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer