apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-frontend
  template:
    metadata:
      labels:
        app: shopping-frontend
    spec:
      containers:
        - name: shopping-frontend
          image: maeddes/hse25frontend:flask
          ports:
            - containerPort: 5000
          env:
            - name: API_SERVER_URL
              value: "http://shopping-api-service:8000"
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-service
spec:
  selector:
    app: shopping-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: shopping-frontend-loadbalancer
spec:
  selector:
    app: shopping-frontend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer